dist: xenial
language: python
services:
  - docker
python:
  - "3.6-dev"
branches:
    only:
        - master
install:
  - pip install -r backend/requirements.txt
script:
    - python backend/manage.py test
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME registry.cn-hangzhou.aliyuncs.com --password-stdin
  - docker build -t co1in backend/
  - docker tag co1in:latest registry.cn-hangzhou.aliyuncs.com/co1in/co1in:$(TRAVIS_BUILD_NUMBER)
  - docker push registry.cn-hangzhou.aliyuncs.com/co1in/co1in:$(TRAVIS_BUILD_NUMBER)