dist: xenial
language: python
services:
  - docker
python:
  - "3.6-dev"
branches:
    only:
        - master
install:
  - pip install -r backend/requirements.txt
script:
    - python backend/manage.py test
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com